Traceback (most recent call last):
  File "/beegfs/scratch/ric.broccoli/kubacki.michal/GSE98969/filter_data.py", line 14, in <module>
    dam_data = pd.read_csv(os.path.join(output_dir, "dam_data_bulk_like.csv"), index_col=0)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kubacki.michal/.conda/envs/jupyter_nb/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kubacki.michal/.conda/envs/jupyter_nb/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kubacki.michal/.conda/envs/jupyter_nb/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kubacki.michal/.conda/envs/jupyter_nb/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/kubacki.michal/.conda/envs/jupyter_nb/lib/python3.11/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/beegfs/scratch/ric.broccoli/kubacki.michal/GSE98969/dam_data_bulk_like.csv'
